#+TITLE: Configuración Eléctrica del Generador FV en un SFCR
#+SUBTITLE: Energía Solar Fotovoltaica
#+SETUPFILE: config.org
#+OPTIONS: H:2

* Configuración Eléctrica del Generador

** Modulos en serie

-  El inversor está diseñado para soportar una *tensión máxima en la
   entrada*, $V_{max,inv}$.

   Superarla puede conllevar la *avería* del equipo.

  #+begin_export latex
  \[
    \max(V_{ocG}) < V_{max,inv}
  \]
  #+end_export
-  El algoritmo de *búsqueda del MPP* se realiza en un
   rango de tensiones limitado, $V_{mppMIN}, V_{mppMAX}$.

   Para *evitar pérdidas* por trabajar en un punto alejado del MPP, la tensión del generador debe estar dentro de este rango:

  #+begin_export latex
  \[
    V_{mppMIN} \leq V_{mppG} \leq V_{mppMAX}
  \]
  #+end_export
** Procedimiento de cálculo
#+BEAMER: \framesubtitle{Tensión máxima}

- Temperatura de célula ($G=\SI{200}{\watt\per\meter\squared},\, T_{a}=\SI{-10}{\celsius}$)
#+begin_export latex
\[
  T_{c} = T_{a} + G \cdot \frac{NOCT-20}{800} \rightarrow   T_{c} = -10 + 200 \cdot \frac{NOCT-20}{800}
\]
#+end_export

- Tensión del módulo
#+begin_export latex
\[
  V_{ocM} = V_{ocM}^{*} + (T_{c}-T_{c}^{*})\cdot\frac{dV_{oc}}{dT_{c}} \rightarrow V_{ocM} = V_{ocM}^{*} + (T_{c}- 25)\cdot\frac{dV_{oc}}{dT_{c}}
\]
#+end_export
- Número de módulos en serie
#+begin_export latex
\[
      V_{ocG} = N_s \cdot V_{ocM} \rightarrow N_{sMAX}=\frac{V_{max,inv}}{V_{ocM}}
\]
#+end_export

** Procedimiento de cálculo
#+BEAMER: \framesubtitle{Tensión MPP}
- Temperatura de célula ($G_{stc},\, T_{a}=\SI{25}{\celsius}$)
#+begin_export latex
\[
  T_{c} = T_{a} + G \cdot \frac{NOCT-20}{800} \rightarrow T_{c} = 25 + 1000 \cdot \frac{NOCT-20}{800}
\]
#+end_export
- Tensión de circuito abierto del módulo
#+begin_export latex
\[
  V_{ocM} = V_{ocM}^{*} + (T_{c}-T_{c}^{*})\cdot\frac{dV_{oc}}{dT_{c}} \rightarrow
  V_{ocM} = V_{ocM}^{*} + (T_{c}- 25)\cdot\frac{dV_{oc}}{dT_{c}}
\]
#+end_export
** Procedimiento de cálculo
#+BEAMER: \framesubtitle{Tensión MPP}

- Tensión MPP del módulo
#+begin_export latex
\[
  V_{mppM} = V_{ocM} \cdot \frac{V_{mppM}^*}{V_{ocM}^*}
\]
#+end_export
- Número de módulos en serie
#+begin_export latex
\[
  V_{mppG} = N_s \cdot V_{mppM} \rightarrow
  \begin{cases}
    N_{sMPP}^{min} =\frac{V_{mppMIN}}{V_{mppM}}\\
    \\
    N_{sMPP}^{max} = \frac{V_{mppMAX}}{V_{mppM}}
  \end{cases}
\]
#+end_export
** Ramas en paralelo

- El fabricante del inversor elige los componentes para soportar una *corriente máxima admisible*.

- En general, el inversor es capaz de autoprotegerse ante valores superiores a este umbral desplazando el punto de funcionamiento del generador fuera del MPP.

- No obstante, el diseñador del sistema debe elegir el número de ramas en paralelo de forma que no se supere este umbral.

#+begin_export latex
\[
    N_{pMAX}=\frac{I_{max,INV}}{I_{scM}^{*}}
\]
#+end_export

** Configuración del generador

De los cálculos anteriores se obtiene un *conjunto de configuraciones* del generador que permiten un buen acoplamiento entre inversor y generador. 

Para *elegir una configuración* deben tenerse en cuenta diferentes aspectos:

- Configuración eléctrica y ubicación física de los módulos en la
  estructura.

- Inversión y rendimiento económicos.

- Espacio disponible.

- Relación de potencias de generador e inversor.

- La curva de eficiencia del inversor depende de la tensión de entrada.

** Configuración eléctrica y estructura

-  Es recomendable elegir *series* compuestas por un número de módulos
   que puedan ser ubicados en una *única hilera de la estructura*.

   -  *Se facilita el trazado del cableado*:

     La propia estructura puede servir como fijación auxiliar, se
     evitan cruzamientos indeseados.

   -  *Se minimiza la influencia de las sombras*:

     Es muy frecuente la aparición de sombras entre partes del
     generador o entre seguidores, sombras de forma rectangular y que
     comienzan afectando a las partes bajas de la estructura. Al
     cablear por hileras, las sombras de las hileras bajas no afectan
     a las hileras inmediatamente superiores.

** Inversión y rendimiento económicos

-  La potencia del generador fotovoltaico está relacionada directamente
   con la *inversión económica* a realizar.

-  Por otra parte, la relación entre *energía generada* y potencia
   nominal es aproximadamente lineal, y por tanto, los *ingresos
   económicos* dependen casi linealmente de la potencia del generador.

-  Por tanto, para decidir la potencia del generador
   ($P_{g}^{*}=N_{s}\cdot N_{p}\cdot P_{m}^{*}$) debe tenerse en cuenta
   el capital o financiación disponible, y el rendimiento económico
   deseado.

** Terreno ocupado

- La potencia del generador es proporcional al área del generador y al *terreno ocupado* (que también influye, aunque en menor grado, en el cálculo económico).

- Por tanto, debe tenerse en cuenta el espacio disponible (o el coste que se pretende asumir por el uso de terreno).

** Relación de potencias entre generador e inversor

Dado que la potencia entregada por el generador varía con las condiciones meteorológicas, el inversor trabajará en diferentes zonas de su curva de eficiencia.

#+ATTR_LATEX: :height 0.75\textheight
[[../figs/CurvaInversor.pdf]]

 
** Relación de potencias entre generador e inversor

- Por tanto, una de las preguntas a responder es *que relación debe existir entre la potencia del generador FV y el inversor*.

#+begin_export latex
\[
  F_{DI} = P_{g}^{*}/P_{inv}
\]
#+end_export

- Si esta relación es alta, el inversor trabajará con frecuencia en la región de alta eficiencia, pero a cambio es posible que deba limitar la potencia del generador para evitar superar su umbral de corriente admisible.

** Relación de potencias entre generador e inversor

- Según el *tipo de sistema* (estático, seguimiento) se debe elegir una relación de potencias de generador e inversor.

- En *sistemas de seguimiento* esta probabilidad suele ser alta. Se recomiendan inversores de potencia similar a la del generador  ($P_{g}^{*}/P_{inv}\in\left[1;1.2\right]$)

- No obstante, es posible demostrar que el valor de esta relación no es tan crítico como *elegir un inversor con buena curva de eficiencia*.

* Cableado Eléctrico

** Características básicas

   - Criterio de caída de tensión.

   - Comprobar intensidad máxima admisible.

   - En sistemas de gran tamaño reducir bucles.

** Criterio de Caída de Tensión

- En primer lugar se calculan las secciones mediante el criterio de caida de tensión (RBT ITC-BT-07):

#+BEGIN_EXPORT latex
\begin{align*}
    S_{dc} &=  \frac{2 \cdot L_{dc}\cdot I_{dc}}{\gamma_\theta \cdot \Delta V_{dc}}\\
    S_{1ac} &=  \frac{2\cdot L_{1ac}\cdot I_{1ac}}{\gamma_\theta \cdot \Delta V_{1ac}}\\
    S_{3ac} &= \frac{\sqrt{3} \cdot L_{3ac}\cdot I_{3ac}}{\gamma_\theta \cdot \Delta V_{3ac}}
  \end{align*}
#+END_EXPORT

- La conductividad del cable, $\gamma_\theta$, depende del material y de la
  temperatura de operación. Por ejemplo, el cobre:
  - $\gamma_{20} = \qty{58}{\meter\per\ohm\per\milli\meter\squared}$
  - $\gamma_{70} = \qty{48}{\meter\per\ohm\per\milli\meter\squared}$.

** Criterio de Caída de Tensión

- Según el apartado 5 de la ITC-BT-40, se exige una caída máxima de
  tensión $\SI{1.5}{\percent}$ de la tensión nominal.

- Para aplicar correctamente este porcentaje es importante caer en la
  cuenta de que *cada zona (DC y AC) tiene su propia tensión nominal*.

** Cálculo

*** Ejemplo
- En una instalación que conduce $\SI{75}{\ampere}$ a la salida de un
  inversor trifásico, situado este a $\SI{100}{\meter}$ de la conexión
  a red, se deberá utilizar un cable de sección (teniendo en cuenta
  que $\gamma_{70} = \SI{48}{\meter\per\ohm\per\milli\meter\squared}$).


#+BEGIN_EXPORT latex
\[
  S=\frac{\sqrt{3} \cdot 100 \cdot 75}{48 \cdot \SI{1.5}{\percent}\cdot400}=\SI{45.46}{\milli\meter\squared}
\]
#+END_EXPORT

- Dado que la sección de los cables está normalizada, se deberá optar
  por la sección inmediatamente superior, y por tanto la conexión del
  inversor a la red se realizará con tres cables de sección
  $S=\SI{50}{\milli\meter\squared}$.

** Intensidad Máxima Admisible

- Con este resultado, es necesario comprobar que la intensidad de diseño es inferior a la intensidad máxima admisible del cable para sus condiciones de servicio, según las tablas de la ITC-BT-07.

- No obstante, las secciones que resultan del criterio de caída de tensión aplicado a los sistemas fotovoltaicos habitualmente son sobradamente capaces de conducir la corriente del sistema.

** Continua vs. Alterna

Suponiendo que en una planta con varios inversores trifásicos existe la
posibilidad de ubicar los inversores debajo del generador FV
(/distribución en alterna/) o en un centro específico junto al punto de
conexión a red (/distribución en continua/), *¿cuál es la tensión de
trabajo en continua que permite optar por una distribución en continua?*

Se puede demostrar que para tensiones de generador $V_{mpp} \geq
\qty{473}{\volt}$, la distribución en continua es preferible a la
distribución en alterna desde el punto de vista de masa de conductor
necesario.


