#+TITLE: Geometría Solar

#+SETUPFILE: config.org
#+OPTIONS: H:3

* Geometría Sol y Tierra
** Movimiento Sol-Tierra

*** Introducción

-  La Tierra se mueve alrededor del Sol siguiendo una elipse de baja
   excentricidad.

   -  Periodo aproximado: 1 año.

   -  Este movimiento está contenido en el llamado /plano de la
      eclíptica/

-  La Tierra gira sobre si misma alrededor de su eje polar.

   -  Entre el eje polar y el plano de la eclíptica hay un ángulo
      constante de $23,45\degree$.

   -  Entre el plano ecuatorial y la linea que une Tierra-Sol hay un
      ángulo variable: /declinación./

*** Movimiento Sol-Tierra

[[../figs/PlanoEcliptica.pdf]]

*** Distancia Sol-Tierra

- Distancia Sol-Tierra

\[r=r_{0}\{1+0.017\sin[\frac{2\pi\cdot(d_{n}-93)}{365}]\}\]

- Distancia promedio

\[r_{0}=\SI{1.496e8}{\kilo\metre}=\SI{1}{UA}\]

- Excentricidad

\[\epsilon_{0}=(\frac{r_{0}}{r})^2=1+0,033\cdot\cos(\frac{2\pi
  d_{n}}{365})\]



*** Declinación

\[\delta=23,45\degree\cdot\sin\left(\frac{2\pi\cdot\left(d_{n}+284\right)}{365}\right)\]

[[../figs/Declinacion.pdf]]

*** Otras ecuaciones
#+BEGIN_LaTeX
\begin{align*}
  X &= 2 \pi \cdot (d_n-1)/365\\
  \delta &= 0.006918 - 0.399912 \cdot \cos(X) + 0.070257 \cdot \sin(X)\\
    &-  0.006758 \cdot \cos(2 X) + 0.000907 \cdot \sin(2 X)\\
    &- 0.002697 \cdot \cos(3 X) + 0.001480 \cdot \sin(3 X)\\
  \epsilon_{0} &= 1.000110 + 0.034221 \cdot \cos(X) + 0.001280 \cdot \sin(X)\\
    &+ 0.000719 \cdot \cos(2 X) + 0.000077 \cdot \sin(2 X)
\end{align*}
#+END_LaTeX

*** Otras ecuaciones

[[../figs/DeclinacionDiferencias.pdf]]

*** Declinación

-  *Equinoccio de primavera*:

   -  21-22 Marzo (Dia del Año 80-81)

-  *Equinoccio de otoño:*

   -  22-23 Septiembre (Dia del Año 265-266)

-  *Solsticio de Verano*:

   -  21-22 Junio (Dia del Año 172-173)

-  *Solsticio de Invierno:*

   -  21-22 Diciembre (Dia del Año 355-356)

*** Declinación

-  Las estaciones se deben al ángulo entre plano ecuatorial y plano de
   la eclíptica

-  *Solsticio de verano*

   -  Declinación máxima.

   -  Días más largos en hemisferio Norte.

   -  El Sol amanece por el Noreste y anochece por el Noroeste en el
      hemisferio Norte.

-  *Solsticio de invierno*

   -  Declinación mínima.

   -  Días más cortos en hemisferio Norte.

   -  El Sol amanece por el Sureste y anochece por el Suroeste en el
      hemisferio Norte.

-  *Equinoccios*

   -  Declinación nula

   -  La duración de noche y día coincide.

   -  El Sol amanece por el Este y anochece por el Oeste.

** Sistemas de coordenadas

*** Ejes terrestres

[[../figs/SoldesdeTierra.pdf]]

\[\vec{\mu}_{s}=\left[\cos\left(\delta\right)\cos\left(\omega\right)\right]\cdot\vec{\mu}_{ec}+\left[\cos\left(\delta\right)\sin\left(\omega\right)\right]\cdot\vec{\mu}_{\bot}+\sin\left(\delta\right)\cdot\vec{\mu}_{p}\]



*** Ejes terrestres

#+ATTR_LATEX: :height 0.7\textheight
[[../figs/SistemaCoordenadasTerrestre.pdf]]


\[\vec{\mu}_{s}=\left[\cos\left(\delta\right)\cos\left(\omega\right)\right]\cdot\vec{\mu}_{ec}+\left[\cos\left(\delta\right)\sin\left(\omega\right)\right]\cdot\vec{\mu}_{\bot}+\sin\left(\delta\right)\cdot\vec{\mu}_{p}\]


*** Ejes locales

[[../figs/SoldesdeTierra2.pdf]]

\[\vec{\mu}_{s}=\left[\cos\left(\psi_{s}\right)\sin\left(\theta_{z}\right)\right]\cdot\vec{\mu}_{h}+\left[\sin\left(\psi_{s}\right)\sin\left(\theta_{z}\right)\right]\cdot\vec{\mu}_{\bot}+\cos\left(\theta_{z}\right)\cdot\vec{\mu}_{c}\]



*** Ejes locales

[[../figs/SistemaCoordenadasLocal.pdf]]

\[\vec{\mu}_{s}=\left[\cos\left(\psi_{s}\right)\sin\left(\theta_{z}\right)\right]\cdot\vec{\mu}_{h}+\left[\sin\left(\psi_{s}\right)\sin\left(\theta_{z}\right)\right]\cdot\vec{\mu}_{\bot}+\cos\left(\theta_{z}\right)\cdot\vec{\mu}_{c}\]

*** Relación entre sistemas de coordenadas

[[../figs/RelacionSistemasCoordenadas.pdf]]

*** Ejes locales y terrestres
#+BEGIN_LaTeX
\begin{align*}
  \vec{\mu}_{s} &= \mathrm{signo}(\phi)\cdot\left[\cos\left(\delta\right)\cos\left(\omega\right)\sin\left(\phi\right)-\cos\left(\phi\right)\sin\left(\delta\right)\right]\cdot\vec{\mu}_{h}-\\
  &- \left[\cos\left(\delta\right)\sin\left(\omega\right)\right]\cdot\vec{\mu}_{\bot}+\\
  &+ \left[\cos\left(\delta\right)\cos\left(\omega\right)\cos\left(\phi\right)+\sin\left(\delta\right)\sin\left(\phi\right)\right]\cdot\vec{\mu}_{c} 
\end{align*}
#+END_LaTeX

*Latitud ($\phi$) con signo*: Positivo para Hemisferio Norte, Negativo para Hemisferio Sur.

** Ángulos Solares

*** Ecuaciones
- Cenit solar
\[\cos\left(\theta_{z}\right)=\vec{\mu}_{c}\cdot\vec{\mu}_{s}=\cos\left(\delta\right)\cos\left(\omega\right)\cos\left(\phi\right)+\sin\left(\delta\right)\sin\left(\phi\right)\]

- Azimut solar
#+BEGIN_LaTeX
\begin{align*}
  \vec{\mu_{s}}\cdot\vec{\mu}_{\bot} &=-\sin\left(\psi_{s}\right)\sin\left(\theta_{zs}\right)\\
  \vec{\mu_{s}}\cdot\vec{\mu}_{h} &=\mathrm{signo}(\phi)\cdot\cos\left(\psi_{s}\right)\sin\left(\theta_{zs}\right)\\
  \cos\left(\psi_{s}\right) &= \mathrm{signo}(\phi)\cdot\frac{\cos\left(\delta\right)\cos\left(\omega\right)\sin\left(\phi\right)-\cos\left(\phi\right)\sin\left(\delta\right)}{\sin\left(\theta_{zs}\right)}\\
  \sin(\psi_{s}) &=\frac{\cos(\delta)\sin(\omega)}{\sin(\theta_{zs})}=\frac{\cos(\delta)\sin(\omega)}{\cos(\gamma_{s})}
\end{align*}
#+END_LaTeX


*** Trayectoria Solar ($60\degree N$)

[[../figs/TrayectoriaSolar60N.pdf]]



*** Trayectoria Solar ($40\degree S$)

[[../figs/TrayectoriaSolar40S.pdf]]


*** Mediodía, amanecer y anocher

-  Mediodía: \[\psi_{s}=0\Rightarrow\sin(\psi_{s})\Rightarrow\omega=0\]

-  Amanecer / Anochecer:
   \[\gamma_{s}=0,\,\theta_{z}=\frac{\pi}{2}\Rightarrow\cos(\theta_{z})=0\]
\[\cos(\omega_{s})=-\tan(\delta)\tan(\phi)\]

*** Duración del día

[[../figs/DuracionDia.pdf]]

*** Cálculo Ángulos Solares

-  Azimut, Ángulo Cenital y Altura Solar, Duración del Dia para el:

   -  Día del Año: 120, 2 horas después del mediodía, Latitud: 37.2N

   -  Día del Año: 340, 2 horas después del amanecer, Latitud: 15S

-  Duración del día 261 del año en las latitudes 10N, 40N, 70N, 10S,
   40S, 70S.

-  Altura solar en el mediodía del día 25 del año en las latitudes 10N,
   40N, 10S, 40S.

** Hora solar y oficial
*** Hora oficial

-  *La hora oficial* es una medida del tiempo *ligada a un meridiano*
   que sirve de referencia para una zona determinada.

-  La hora oficial de la España peninsular se rija por el huso horario
   de Centroeuropa. Este huso horario está situado en
   $15\degree\mathrm{E}$.

*** Hora oficial

-  *Corrección*: $\Delta\lambda=\lambda_{L}-\lambda_{H}$, con
   $\lambda_{L}$ la longitud local y $\lambda_{H}$ la longitud del huso
   horario.

-  Longitudes /positivas/ al /este/ del meridiano de Greenwich.
   $\Delta\lambda$ es positiva cuando la localidad está situada al este
   de su huso horario.

-  Diferencia adicional: /horario de verano/.

*** Tiempo solar medio

-  *La duración del día solar real*, definido como el tiempo que
   transcurre entre dos pasos consecutivos del Sol por el meridiano
   local, *varía a lo largo del año*.

-  El promedio anual de esta variación es nulo: /día solar medio/, cuya
   duración es constante a lo largo del año e igual al valor medio de la
   duración del día solar real.

*** Ecuación del Tiempo

$\mathrm{EoT}=229.18\cdot\left(-0.0334\cdot\sin(M)+0.04184\cdot\sin\left(2\cdot
      M+3.5884\right)\right)$

[[../figs/EoT.pdf]]

*** Ejemplo de cálculo

\[\omega=15\cdot(\mathrm{TO}-\mathrm{AO}-12)+\Delta\lambda+\frac{\mathrm{EoT}}{4}\]

-  Calculemos la hora solar real correspondiente al día 23 de Abril
   de 2010 a las 12 de la mañana, hora oficial de la ciudad de A Coruña,
   Galicia.
\pause
-  Esta localidad está contenida en el meridiano de longitud
   $8.38\degree\mathrm{W}$ y su hora oficial está regida por el huso
   horario GMT+1.
\pause
-  Por tanto $\lambda_{L}=-8.38\degree$, $\lambda_{H}=15\degree$ y
   $\Delta\lambda=-23.38\degree$.
\pause
-  En España se aplica el horario de verano y este día está incluido
   en el período afectado, $\mathrm{AO}=1$.
\pause
-  Por último, para este día $\mathrm{EoT=\SI{1.78}{\minute}}$.
\pause
-  Así $\omega=-37.94\degree$ (aproximadamente las 9 y media de la
   mañana). El Sol culminará ($\omega=0$) cuando sean las 14:31, hora
   oficial.


* Geometría de los sistemas fotovoltaicos

** Inclinación y Orientación

*** Acimutal 
[[../figs/Sombra2X.pdf]]

#+BEGIN_LaTeX
\begin{align*}
  \beta &= cte.\\
  \alpha &= \psi_{s}\\
  \cos(\theta_{s}) &= \cos\left(\beta-\theta_{z}\right)
\end{align*}
#+END_LaTeX



*** Acimutal, ($40\degree N$)

[[../figs/AlfaDoble_40N.pdf]]

*** Doble Eje
[[../figs/Sombra2X.pdf]]

#+BEGIN_LaTeX
\begin{align*}
  \beta &= \theta_{z}\\
  \alpha &= \psi_{s}\\
  \cos(\theta_{s}) &= 1
\end{align*}
#+END_LaTeX


*** Doble Eje, ($40\degree N$)

[[../figs/BetaDoble_40N.pdf]]



** Ángulo de Incidencia

*** Sistema Estático
- Vector de posición
\[\vec{\mu}_{\beta}=[\sin(\beta)\cos(\alpha)]\cdot\vec{\mu}_{h}+[\sin(\beta)\sin(\alpha)]\cdot\vec{\mu}_{\bot}+\cos(\beta)\cdot\vec{\mu}_{c}\]

[[../figs/AngulosSistemaEstatico.pdf]]

*** Sistema Estático
- Ángulo de Incidencia
#+BEGIN_LaTeX
\begin{align*}
\cos(\theta_{s}) &= \mathrm{signo}(\phi)\cdot\bigl[\sin(\beta)\cos(\alpha)\cos\left(\delta\right)\cos\left(\omega\right)\sin\left(\phi\right)-\\
 &- \sin(\beta)\cos(\alpha)\cos\left(\phi\right)\sin\left(\delta\right)\bigr]+\\
 &+ \sin(\beta)\sin(\alpha)\cos\left(\delta\right)\sin\left(\omega\right)+ \\
 &+ \cos(\beta)\cos\left(\delta\right)\cos\left(\omega\right)\cos\left(\phi\right)+\\
 &+ \cos(\beta)\sin\left(\delta\right)\sin\left(\phi\right)
\end{align*}
#+END_LaTeX

#+ATTR_LATEX: :height 0.4\textheight
[[../figs/AngulosSistemaEstatico.pdf]]


*** Sistema Estático
Cuando $\alpha=0$
#+BEGIN_LaTeX
\begin{align*}
\cos(\theta_{s}) &= \cos\left(\delta\right)\cos\left(\omega\right)\cos\left(\beta-|\phi|\right)-\\ 
&- \mathrm{signo}(\phi)\cdot\sin(\delta)\sin\left(\beta-|\phi|\right)
\end{align*}
#+END_LaTeX

#+ATTR_LATEX: :height 0.6\textheight
[[../figs/AngulosSistemaEstatico.pdf]]


*** Sistema Estático 

- $40\degree N$

[[../figs/cosThetaEst_40N.pdf]]



*** Eje Horizontal N-S, generador horizontal


- Vector de posición

\[\vec{\mu}_{ns}=\sin(\psi_{ns})\cdot\vec{\mu}_{\bot}+\cos(\psi_{ns})\cdot\vec{\mu}_{c}\]

#+ATTR_LATEX: :height 0.6\textheight
[[../figs/AngulosSistemaHorizontalNS.pdf]]



*** Eje Horizontal N-S, generador horizontal

- Ángulo de Incidencia

\[\cos(\theta_{s})=\cos(\delta)\sqrt{\sin^{2}(\omega)+\left(\cos(\omega)\cos(\phi)+\tan(\delta)\sin(\phi)\right)^{2}}\]

#+ATTR_LATEX: :height 0.6\textheight
[[../figs/AngulosSistemaHorizontalNS.pdf]]


*** Eje Horizontal N-S, generador horizontal, ($40\degree N$)

[[../figs/BetaHoriz_40N.pdf]]



*** Eje Horizontal N-S, generador horizontal, ($40\degree N$)

[[../figs/cosThetaHoriz_40N.pdf]]


*** Acimutal, ($40\degree N$)

[[../figs/cosThetaAzimutal_40N.pdf]]


*** Cálculo de ángulo de incidencia

-  Para: ::

   - Un sistema estático orientado al Sur y con inclinación de 30;

   - Un sistema de seguimiento horizontal N-S;

   - Un sistema de seguimiento acimutal con inclinación a 35;

   - Un sistema de seguimiento a doble eje,

-  Calcular :: el ángulo de incidencia para el:

   - Día del Año: 120, 2 horas después del mediodía, Latitud: 37.2N;

   - Día del Año: 340, 2 horas después del amanecer, Latitud: 15S;
