#+TITLE: Inversores para Centrales Fotovoltaicas
#+SUBTITLE: Energía Solar Fotovoltaica
#+SETUPFILE: config.org
#+OPTIONS: H:2


* Conceptos Generales
** Acoplamiento a la red

*** 
La potencia suministrada por un generador fotovoltaico iluminado es de
tensión continua, que debe ser adecuadamente acondicionada para permitir
el funcionamiento correcto de las cargas conectadas en un sistema
autónomo o el acoplamiento a la red eléctrica en el caso de sistemas de
conexión a red.

** Definición


[[../figs/SFCR_Esquema.pdf]]


- El equipo de acondicionamiento de potencia, denominado inversor DC/AC, realiza la *conversión de continua a alterna cumpliendo con  determinados requisitos* de tensión eficaz, frecuencia, distorsión armónica de las ondas de tensión y corriente, rendimiento instantáneo y medio, seguridad eléctrica, etc.

- Funciona como fuente de corriente autoconmutada y sincronizada con la red.

** Tipos de Inversores
A grandes rasgos, los inversores pueden agruparse en tres categorías:

-  *Inversor central*: un único inversor dedicado a todo el generador (o
   a un conjunto de ramas)

-  *Inversor orientado a rama* (/string-inverter/): un inversor dedicado
   a una rama del generador.

-  *Módulo-AC*: un inversor dedicado a un módulo del generador.

** Inversores Centrales

-  Los *inversores centrales* son recomendables para instalaciones de
   medio o gran tamaño. Permiten reducir costes (de adquisición,
   instalación y mantenimiento) y aumentar fiabilidad y eficiencia.

\vfill

-  *La potencia del inversor debe estar en consonancia con la potencia
   del generador* (una planta de 1 MWp debiera contar con 10 inversores
   de 100 kW o 4 de 250 kW, pero no con 200 de 5 kW).

* Características básicas
** Potencia y ventana MPP

-  *Potencia nominal y máxima*, siendo ésta un porcentaje de sobrecarga
   que el equipo es capaz de soportar durante un determinado período de
   tiempo (indicado por el fabricante).

-  *Ventana de búsqueda del Punto de Máxima Potencia* (MPP en siglas
   inglesas): es el rango de tensiones en las que el inversor aplica un
   algoritmo de búsqueda del MPP del generador fotovoltaico.

** Tensiones

-  *Tensión máxima de entrada*: es la máxima tensión que el inversor
   puede aguantar sin sufrir una avería.

-  *Tensión nominal de salida*: es la tensión de red a la que se puede
   conectar el inversor (habitualmente 230 Vac para equipos monofásicos
   y 400 Vac para equipos trifásicos).

-  *Umbral de arranque*: según las unidades en las que se expresa, puede
   indicar la radiación solar incidente en el generador
   ($\si{\watt\per\meter\squared}$) o la potencia de entrada (W)
   necesaria para que el inversor comience el proceso de conversión.

** Eficiencia

- *Eficiencia del inversor*, $\eta_{inv} = P_{ac} / P_{dc}$ 

- Esta relación puede describirse con una función basada en tres
  coeficientes y la normalización de la potencia de salida,
  $p_{o}=P_{ac}/P_{inv}$:
  $$\eta_{inv}=\frac{p_{o}}{p_{o}+k_{0}^{o}+k_{1}^{o}p_{o}+k_{2}^{o}p_{o}^{2}}$$

- *Eficiencia máxima*: máximo valor que toma la relación entre
  potencia de salida y potencia de entrada. En inversores de calidad
  la eficiencia es estable en un amplio rango de funcionamiento del
  equipo y de un valor cercano a la eficiencia máxima.


** Ejemplo de curva de eficiencia

***                                                                   :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.8
:END:
#+ATTR_LATEX: :height 0.9\textheight
[[../figs/CurvaInversor.pdf]]


***                                                                   :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.2
:END:
$k_{0}^{o}=0.01$

$k_{1}^{o}=0.025$

$k_{2}^{o}=0.05$

** Rendimiento

- *Rendimiento*: es la relación entre la energía entregada por
  un inversor que recibe una energía producida por un generador
  fotovoltaico funcionando en unas determinadas condiciones de radiación.

- *Rendimiento europeo*: condiciones de radiación características del
  clima de la zona centroeuropea.
  #+begin_export latex
  \[
    \eta_{euro} = 0.03 \cdot \eta_{5\%}  +  0.06 \cdot \eta_{10\%}  +  0.13 \cdot \eta_{20\%}  +  0.1 \cdot \eta_{30\%}  +  0.48 \cdot \eta_{50\%}  +  0.2 \cdot \eta_{100\%}
  \]
  #+end_export
- *Rendimiento CEC*: condiciones de radiación características del clima de
  California.
  #+begin_export latex
  \[
    \eta_{CEC} = 0.04 \cdot \eta_{10\%}  +  0.05 \cdot \eta_{20\%}  +  0.12 \cdot \eta_{30\%}  +  0.21 \cdot \eta_{50\%} + 0.53 \cdot \eta_{75\%}  +  0.05 \cdot \eta_{100\%}
  \]
  #+end_export

** Distorsión armónica
Cuando una señal sinusoidal atraviesa un circuito no lineal (diodos, transistores) aparecen señales (armónicos) de frecuencias múltiplo de la original (fundamental).


#+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/DistorsionArmonica.pdf]]


** Distorsión armónica
La distorsión armónica total (THD) es la relación entre la potencia de los armónicos superiores al fundamental ($n > 2$) y la potencia del fundamental.

#+begin_export latex
\[
  THD_I = \frac{1}{I_1} \cdot \sqrt{\sum_{n = 2}^\infty I_n^2} 
\]
#+end_export

Los inversores de conexión a red suministran una señal de calidad, con $THD < 3\%$ o inferiores.

* Composición
** Entrada
[[../figs/InversorPV.pdf]]

-  *Filtro de entrada*: atenúa el rizado que produce la conmutación en
   la corriente de entrada

-  *Convertidor DC/DC*: adecúa (eleva o reduce) la tensión de salida del
   generador a la tensión necesaria para el puente de conmutación. Puede
   realizar las funciones de búsqueda del punto de máxima potencia.

** Puente y salida

[[../figs/InversorPV.pdf]]

-  *Puente inversor*: realiza el troceado de la señal continua para
   convertirla en alterna

-  *Filtro de salida*: elimina o atenúa los armónicos no deseados

-  *Transformador*: adecua el valor de tensión de salida del puente al
   de la red y proporciona aislamiento galvánico entre la parte DC y
   AC.

** Control

[[../figs/InversorPV.pdf]]

-  *Control*: realiza la supervisión de la entrada y salida del
   convertidor DC/DC y del puente inversor y entrega las consignas
   correspondientes para localizar y seguir el MPP del generador, y para
   obtener una señal sinusoidal con bajo contenido en armónicos en la
   salida del inversor.

* Funcionamiento

** Modulación SPWM (monofásico)
#+ATTR_LATEX: :height 0.9\textheight
[[../figs/SPWMMonofasico.pdf]]

** Modulación SPWM (trifásico)
#+ATTR_LATEX: :height 0.9\textheight
[[../figs/SPWMTrifasico.pdf]]

** Modulación SPWM (trifásico)
#+ATTR_LATEX: :height 0.9\textheight
[[../figs/SPWMTrifasico_shaded.pdf]]

** Busqueda del Punto de Máxima Potencia
#+ATTR_LATEX: :height 0.6\textheight
[[../figs/CurvaIV_Ta20_G800.pdf]]

$$\begin{cases}
      \frac{dP}{dV}>0 & 0<V<V_{mpp}\\
      \frac{dP}{dV}=0 & V=V_{mpp}\\
      \frac{dP}{dV}<0 & V_{mpp}<V<V_{oc}\end{cases}$$

** Busqueda del Punto de Máxima Potencia
#+ATTR_LATEX: :height 0.6\textheight
[[../figs/CurvaIV_Ta20_G800.pdf]]

$$\begin{cases}
      \frac{dI}{dV}>-\frac{I}{V} & 0<V<V_{mpp}\\
      \frac{dI}{dV}=-\frac{I}{V} & V=V_{mpp}\\
      \frac{dI}{dV}<-\frac{I}{V} & V_{mpp}<V<V_{oc}\end{cases}$$

** Transformador de salida

[[../figs/InversorPV.pdf]]

-  El transformador permite adecuar el nivel de tensión de salida del
   puente de conmutación a la tensión de red.

-  La componente inductiva del transformador es parte del filtro de
   salida y sirve como acoplamiento entre la red eléctrica y la salida
   del inversor.

-  Establece el aislamiento galvánico entre la entrada del inversor (DC)
   y la salida (AC).

** Opciones comerciales

Existen tres opciones en el mercado de inversores de conexión a red:

- Inversores con transformador de salida en baja frecuencia

- Inversores con transformador de alta frecuencia

- Inversores sin transformador

** Normativa relativa al transformador

La normativa vigente en España obliga al uso de un transformador de aislamiento o elemento equivalente para cumplir tres objetivos:

1. Aislar la instalación generadora para evitar la transferencia de defectos entre la red y la instalación

2. Proporcionar seguridad personal

3. Evitar la inyección de corriente continua en la red.

** Normativa: Nota de Interpretación Tecnica

-  Objetivos 1 y 2 se consiguen mediante la adecuada conexión de masas y tierras en el sistema.

-  Objetivo 3: "*la corriente continua inyectada en la red de distribución por una instalación generadora no será superior al 0,5% de la corriente nominal de la misma*", cumplido "*cuando se disponga en la instalación de un transformador separador entre el inversor y el punto de conexión de la red de distribución*". /Los inversores con transformador de alta frecuencia o sin transformador deben demostrar el cumplimiento de este requisito mediante un ensayo descrito en esta nota/.

* COMMENT Islanding
** Definición del problema

[[../figs/Isla.pdf]]

** Ecuaciones básicas

Antes de la desconexión:
#+begin_export latex
\begin{align*}
\Delta P^- &=P_{carga}-P_{PV}\\
\Delta Q^- &=Q_{carga}-Q_{PV}\simeq Q_{carga}
\end{align*}
#+end_export

Después de la desconexión:
#+begin_export latex
\begin{align*}
\Delta P^+ &= 0 \rightarrow P_{carga} = P_{PV}\\
\Delta Q^+ &= 0 \rightarrow Q_{carga} = 0
\end{align*}
#+end_export

siendo:

#+begin_export latex
\begin{align*}
P_{carga}&=\frac{V^{2}}{R_{carga}}\\
Q_{carga}&=\frac{V^{2}}{\omega L}-V^{2}\omega C
\end{align*}
#+end_export
** Casos posibles

-  $\Delta P^{-}>0\rightarrow P_{carga}>P_{PV}$. Al producirse la
   desconexión, dado que $P_{PV}$ no cambia, disminuye la potencia
   entregada a la carga, y por tanto baja la tensión.

-  $\Delta P^{-}<0\rightarrow P_{carga}<P_{PV}$. Al producirse la
   desconexión, aumenta la potencia entregada a la carga, y por tanto
   sube la tensión.

-  $\Delta Q^{-}>0\rightarrow Q_{carga}>0$. La carga es inductiva. Al
   producirse la desconexión, dado que el generador FV no entrega
   reactiva, la reactiva debe tender a 0, y por tanto aumenta la
   frecuencia.

-  $\Delta Q^{-}<0\rightarrow Q_{carga}<0$. La carga es capacitiva. La
   reactiva debe tender a cero, y por tanto disminuye la frecuencia.

** Ventana de no-detección

Cuando las condiciones de trabajo del generador y el consumo antes de la
desconexión son muy cercanas, existe una ventana de no-detección.

#+BEGIN_CENTER
#+ATTR_LATEX: :height 0.6\textheight
[[../figs/NDZ.pdf]]
#+END_CENTER

** Estudio experimental IEA-PVPS

-  La probabilidad de que se de una situación de balance entre consumo y
   generación en una red de Baja Tensión está entre $\num{1e-5}$ y
   $\num{1e-6}$.

-  Para que se de una situación de isla, este balance debe coincidir con
   una desconexión de la red: la probabilidad de ocurrencia simultánea
   de estos dos sucesos es virtualmente nula.

** Estudio experimental IEA-PVPS

-  El riesgo eléctrico existente en cualquier red eléctrica es del orden
   de $\num{1e-6}$.

-  Este estudio mostró que el riesgo de accidente eléctrico asociado a
   un sistema fotovoltaico funcionando en isla bajo los escenarios de
   mayor penetración fotovoltaica era inferior a $\num{1e-9}$.

-  Este resultado indica que el riesgo asociado al accidente eléctrico
   por isla FV no incrementa el riesgo que ya existe en las
   instalaciones eléctricas.


