#+TITLE: Sistemas Fotovoltaicos Autónomos
#+SUBTITLE: Diseño

#+SETUPFILE: config.org
#+OPTIONS: H:3

* Dimensionado del SFA
*** Objetivo

- El dimensionado de un SFA consiste en *decidir el tamaño del
  generador fotovoltaico y acumulador* que serán capaces de
  *proporcionar la energía requerida* por una determinada carga a partir
  de la *radiación disponible* en la zona.

- Debido al comportamiento aleatorio tanto de la radiación como del
  consumo, la *probabilidad de fallo no es nula*.

- La solución es un compromiso entre el coste y la fiabilidad del
  sistema.


** Nomenclatura
*** Carga

-  Consumo: :: $L$

-  Probabilidad de pérdida de carga: :: relación entre la energía que no
   puede suministrar el sistema fotovoltaico y la energía solicitada por
   la carga durante todo el período de
   funcionamiento.$$LLP=\frac{E_{def}}{L}$$

*** Capacidades normalizadas

-  Capacidad del generador: :: relación entre los valores medios de la
   energía que puede producir el generador y la energía consumida por la
   carga.
   $$C_{A}=\frac{\eta_{G}\cdot A_{G}\cdot\overline{G_{d}}(\beta,\alpha)}{L}$$

-  Capacidad de acumulación: :: relación entre la capacidad útil del acumulador y la energía consumida por la carga.
$$C_{s}=\frac{C_{U}}{L}=\frac{C_{B}\cdot PD_{max}}{L}$$

** Objetivo
*** Dimensionado
**** La tarea de dimensionar un sistema fotovoltaico consiste en encontrar la mejor solución de compromiso entre coste y fiabilidad.
-  Diferentes valores de $(C_{A},\, C_{S})$ pueden conducir al mismo
   valor de $LLP$.

-  Cuanto mayor es el sistema, mayor es la fiabilidad, pero mayor es el
   coste.


** Ejemplos
*** Generador grande, acumulador pequeño

-  La *combinación de $C_{A}$ alta y $C_{S}$ baja* conduce a ciclados
   diarios con descargas profundas y ciclados estacionales
   cortos.

   -  Las descargas profundas y frecuentes son perjudiciales para la
     batería,

   -  La corta longitud de los ciclados estacionales es beneficiosa.

   -  La estratificación será fácilmente compensable con sobrecargas
      controladas aplicando el mantenimiento adecuado.

*** Generador pequeño, acumulador grande

-  La *combinación de $C_{A}$ baja y $C_{S}$ alta* conduce a ciclados
   diarios con descargas moderadas y ciclados estacionales largos.

   -  La baja profundidad de descarga es beneficiosa para la batería,

   -  La longitud de los ciclados estacionales puede favorecer la
      sulfatación y la estratificación.

   -  Dado el tamaño relativo del generador frente al acumulador, la
      frecuencia de sobrecargas será baja y la estratificación no será
      tan fácilmente compensada.

*** Sistemas Híbridos
- Cuando $LLP$ es muy alta (p.e. radioenlaces) o la demanda es muy
  elevada (poblados) el generador y acumulador serán excesivamente
  grandes.

- Es habitual incluir un grupo electrógeno que suministra la energía
  deficitaria y permite reducir el tamaño del SFA.

- Sinergia:

  - El grupo electrógeno reduce el tamaño del generador FV y el
    acumulador sin reducir fiabilidad.

  - El generador fotovoltaico reduce horas de funcionamiento del
    grupo: gasto en combustible y mantenimiento.

** Métodos de dimensionado
*** Métodos de dimensionado

**** Método del LLP

A partir de simulaciones o de curvas de isofiabilidad, establece los
valores de $C_{A}$ y $C_{S}$ para un consumo determinado.

**** Método del mes peor
- Determina el tamaño de batería y generador para abastecer el consumo durante el mes con peor relación entre radiación y consumo.
- Si el consumo es constante, el mes peor es aquel de menor radiación.
- Recomendaciones de expertos según zona geográfica y aplicación (tipología de consumo).

*** Método del LLP

[[../figs/CurvasLLP.pdf]]

*** Relación entre tamaño de generador y LLP

- $C_{s}=3$

[[../figs/CurvasLLP_Cs3.pdf]]

*** Método de LLP

-  Este proceso de cálculo se apoya en series de valores de radiación
  solar que reproducen el comportamiento estadístico de la
  irradiación.

-  La predicción del comportamiento del sistema limitada por la
  incertidumbre asociada.

-  Los ejercicios de cálculo para probabilidades de pérdida de carga
  inferiores a $LLP=\num{1e-2}$ carecen de utilidad.

**** Recordatorio
"[...] los modelos de simulación muy exactos pueden proporcionar números también muy exactos, pero ello no significa que se traduzcan automáticamente en predicciones también muy exactas."

*** Método del mes peor

**** Valores según el UTS for SHS

- Electrificación rural:

  - $C_{A}=1.1$

  - $3\leq C_{S}\leq5$

- Aplicaciones profesionales:

  - $1.2\leq C_{A}\leq1.3$

  - $5\leq C_{S}\leq8$

** Configuración de generador y batería
*** Configuración de generador y batería

- Una vez elegidos los valores de $C_{A}$ y $C_{S}$, se deben
  configurar el generador y batería de acuerdo a las tensiones de
  trabajo.

- En general, la batería impone la tensión de trabajo (no hay buscador
  de MPP). Supondremos $V_{mpp} \simeq V_{b}$

- Carga en Ah
#+BEGIN_EXPORT latex
\[
Q_L = L / V_b
\]
#+END_EXPORT

*** Batería

- Capacidad en Ah (es recomendable no usar baterías en paralelo)
#+BEGIN_EXPORT latex
\[
Q_B = \frac{C_S \cdot Q_L}{PD}
\]
#+END_EXPORT

- Hay que elegir el número de vasos en serie adecuados a $V_b$


*** Generador
- Capacidad del generador
#+BEGIN_EXPORT latex
\[
C_{A} = \frac{\eta_{G}\cdot A_{G}\cdot\overline{G_{d}}(\beta,\alpha)}{Q_L \cdot V_b}
\]
#+END_EXPORT


- Corriente de funcionamiento (determina número de ramas)

#+BEGIN_EXPORT latex
\begin{align*}
I_{g}^{*}\cdot V_{b} &= \eta_{G}\cdot A_{G}\cdot G_{stc}\\
I_{g}^{*} &=  \frac{C_{A}\cdot Q_{L}\cdot G_{stc}}{\overline{G_{d}}(\beta,\alpha)}
\end{align*}
#+END_EXPORT

- Hay que elegir el número de módulos en serie adecuados a $V_b$

*** Inclinación del generador

-  Para instalaciones con *consumos constantes o similares a lo largo del año*, se busca maximizar la radiación en los meses de menor insolación $$\beta=|\phi|+10^{\circ}$$

-  Para instalaciones con *consumo menor en meses de baja radiación* se busca maximizar radiación en equinoccios.$$\beta=|\phi|$$

-  Para instalaciones con *uso predominante en verano* (hemisferio Norte) conviene emplear un ángulo inferior a la latitud. $$\beta=|\phi|-10^{\circ}$$

-  En general, la inclinación *debe superar* los $15^{\circ}$.

* Consumo

** Estimación del consumo
*** Cálculo del consumo
- Energía total requerida por las cargas
$$L_{T}=\frac{L_{dc}}{\eta_{r}}+\frac{L_{ac}}{\eta_{inv}}$$

- Energía producida por el generador
$$L=\frac{L_{T}}{\eta_{bat}\cdot\eta_{c}}$$

Como valores orientativos pueden utilizarse

$\eta_{inv}=0.9$, $\eta_{r}=0.95$, $\eta_{bat}=0.85$ y $\eta_{c}=0.98$.

*** Distribución del consumo

[[../figs/ConsumoGamma.pdf]]

*** Relación entre el consumo y la fiabilidad
- La variación en el consumo se amplifica en la variación de la LLP.
- Diseño robusto: funcionamiento en amplio abanico de condiciones (ambientales y humanas).
#+ATTR_LATEX: :height 0.7\textheight
[[../figs/ConsumoLLP.pdf]]

** Escenarios de Consumo
*** SHS 1
**** 120 Wh/dia
-  Iluminación

-  Radio

-  TV b/n,

-  Sin frigorífico

**** Valores recomendados 
$$\begin{aligned}
C_{A} & = & 1.1\\
3\leq & C_{s} & \leq5
\end{aligned}$$

*** SHS 2
**** 250 Wh/dia
-  Iluminación

-  Radio

-  TV color

-  Sin frigorífico

**** Valores recomendados 
$$\begin{aligned}
C_{A} & = & 1.1\\
3\leq & C_{s} & \leq5
\end{aligned}$$

*** SHS 3
**** 1000 Wh/dia
-  Iluminación

-  radio

-  TV color

-  Con frigorífico eficiente

**** Valores recomendados 
$$\begin{aligned}
C_{A} & = & 1.1\\
C_{S} & = & 5
\end{aligned}$$

*** Centrales

**** 
-  Todo AC

-  500 Wh/dia por vivienda.

**** Valores recomendados 
$$\begin{aligned}
C_{A} & = & 1.1\\
C_{S} & = & 5\end{aligned}$$
