#+TITLE: SFA: Diseño

#+SETUPFILE: config.org
#+OPTIONS: H:3

* Dimensionado del SFA

** Nomenclatura
*** Carga

-  Consumo: :: $L$

-  Probabilidad de pérdida de carga: :: relación entre la energía que no
   puede suministrar el sistema fotovoltaico y la energía solicitada por
   la carga durante todo el período de
   funcionamiento.$$LLP=\frac{E_{def}}{L}$$

*** Capacidad

-  Capacidad del generador: :: relación entre los valores medios de la
   energía que puede producir el generador y la energía consumida por la
   carga.
   $$C_{A}=\frac{\eta_{G}\cdot A_{G}\cdot\overline{G_{d}}(\beta,\alpha)}{L}$$

-  Capacidad de acumulación: :: relación entre la capacidad útil del acumulador y la energía consumida por la carga.
$$C_{s}=\frac{C_{U}}{L}=\frac{C_{B}\cdot PD_{max}}{L}$$

** Objetivo
*** Dimensionado
**** La tarea de dimensionar un sistema fotovoltaico consiste en encontrar la mejor solución de compromiso entre coste y fiabilidad.
-  Diferentes valores de $(C_{A},\, C_{S})$ pueden conducir al mismo
   valor de $LLP$.

-  Cuanto mayor es el sistema, mayor es la fiabilidad, pero mayor es el
   coste.


** Ciclado
*** Ciclado diario y estacional

-  El *ciclado diario* es la serie de cargas y descargas de la batería
   que se producen durante un periodo diario.

   -  $PD_{d}$, está relacionada con el consumo nocturno, $L_{n}$, y por
      tanto exclusivamente con la capacidad de la batería:
      $PD_{d}=\frac{L_{n}}{C_{B}}$

-  El *ciclado estacional* es la serie de cargas y descargas que se
   producen durante un periodo prolongado de duración variable

   -  La duración, $D$, $PD_{e}$, están ligados al tamaño del generador,
      al consumo diario (diurno y nocturno) y a la radiación disponible.

   -  La batería debe proporcionar la energía necesaria pero
      $PD_{e}<PD_{max}$.

*** Generador grande, acumulador pequeño

-  La *combinación de $C_{A}$ alta y $C_{S}$ baja* conduce a ciclados
   diarios con valores altos de $PD_{d}$ con ciclados estacionales
   cortos.

   -  Las descargas profundas y frecuentes asociadas al valor alto de
      $PD_{d}$ son perjudiciales para la batería,

   -  La corta longitud de los ciclados estacionales es beneficiosa.

   -  La estratificación será fácilmente compensable con sobrecargas
      controladas aplicando el mantenimiento adecuado.

*** Generador pequeño, acumulador grande

-  La *combinación de $C_{A}$ baja y $C_{S}$ alta* conduce a ciclados
   diarios con baja $PD_{d}$ y ciclados estacionales largos.

   -  La baja $PD_{d}$ es beneficiosa para la batería,

   -  La longitud de los ciclados estacionales puede favorecer la
      sulfatación y la estratificación.

   -  Dado el tamaño relativo del generador frente al acumulador, la
      frecuencia de sobrecargas será baja y la estratificación no será
      tan fácilmente compensada.

** Métodos de dimensionado
*** Métodos de dimensionado

-  Método del LLP: :: a partir de simulaciones o de curvas de
   isofiabilidad, establece los valores de $C_{A}$ y $C_{S}$ para un
   consumo determinado.

-  Método del mes peor: :: selecciona el tamaño de batería y generador
   para abastecer el consumo durante el mes con peor relación entre
   radiación y consumo (en los casos de consumo constante, el mes peor
   es aquel de menor radiación). El tamaño de batería y generador se
   selecciona en base a la experiencia acumulada según la zona
   geográfica y la aplicación a abastecer.

*** Método del LLP

**** Suposiciones

-  El consumo es constante a lo largo del año

-  Todo el consumo ocurre por la noche

-  Los componentes del sistema FV no tienen pérdidas (incluidas dentro
   de $C_{A}$ y $C_{S}$) y lineales.

*** Método de LLP

[[../figs/CurvasLLP.pdf]]

*** Relación entre $C_{A}^{'}$ y LLP

- $C_{s}=3$

[[../figs/CurvasLLP_Cs3.pdf]]

*** Método del LLP

- Es posible ajustar las curvas isofiables a una ecuación analítica:

\[
C_{A}^{'} = f\cdot C_{s}^{-u}
\]

- $f$ y $u$ son dos parámetros sin significado físico, dependientes del lugar y del LLP deseado. 
- Para su determinación es necesario realizar varias simulaciones previas.

*** Método de LLP

-  Este proceso de cálculo se apoya en series de valores de radiación solar que reproducen el comportamiento estadístico de la irradiación.

-  Predicción del comportamiento del sistema limitada por la incertidumbre asociada.

-  Los ejercicios de cálculo para probabilidades de pérdida de carga inferiores a $LLP=\num{1e-2}$ carecen de utilidad.

**** Recordatorio
"[...] los modelos de simulación muy exactos pueden proporcionar números también muy exactos, pero ello no significa que se traduzcan automáticamente en predicciones también muy exactas."

*** Método del mes peor

**** Valores según el UTS for SHS

- Electrificación rural:

  - $C_{A}=1.1$

  - $3\leq C_{S}\leq5$

- Aplicaciones profesionales:

  - $1.2\leq C_{A}\leq1.3$

  - $5\leq C_{S}\leq8$

** Configuración de generador y batería
*** Configuración de generador y batería

- Una vez elegidos los valores de $C_{A}$ y $C_{S}$, se deben configurar el generador y batería de acuerdo a las tensiones de trabajo. 

- En general, la batería impone la tensión de trabajo (no hay buscador de MPP). Supondremos $V_{mpp}\simeq V_{b}$

- Carga en Ah
#+BEGIN_LaTeX
\[
Q_L = L / V_b
\]
#+END_LaTeX

*** Batería

- Capacidad en Ah (es recomendable no usar baterías en paralelo)
#+BEGIN_LaTeX
\[
Q_B = \frac{C_S \cdot Q_L}{PD}
\]
#+END_LaTeX

- Hay que elegir el número de vasos en serie adecuados a $V_b$


*** Generador
- Capacidad del generador
#+BEGIN_LaTeX
\begin{align*}
C_{A} &= \frac{\eta_{G}\cdot A_{G}\cdot\overline{G_{d}}(\beta,\alpha)}{Q_L \cdot V_b}\\
I_{g}^{*}\cdot V_{b} &= \eta_{G}\cdot A_{G}\cdot G_{stc} 
\end{align*}
#+END_LaTeX

- Corriente de funcionamiento (determina número de ramas)
#+BEGIN_LaTeX
\[
I_{g}^{*} &=  \frac{C_{A}\cdot Q_{L}\cdot G_{stc}}{\overline{G_{d}}(\beta,\alpha)}
\]
#+END_LaTeX

- Hay que elegir el número de módulos en serie adecuados a $V_b$

*** Inclinación del generador

-  Para instalaciones con *consumos constantes o similares a lo largo del año*, se busca maximizar la radiación en los meses de menor insolación $$\beta=|\phi|+10^{\circ}$$

-  Para instalaciones con *consumo menor en meses de baja radiación* se busca maximizar radiación en equinoccios.$$\beta=|\phi|$$

-  Para instalaciones con *uso predominante en verano* (hemisferio Norte) conviene emplear un ángulo inferior a la latitud. $$\beta=|\phi|-10^{\circ}$$

-  En general, la inclinación *debe superar* los $15^{\circ}$.

* Consumo

** Estimación del consumo
*** Cálculo del consumo

$$L_{T}=\frac{L_{dc}}{\eta_{r}}+\frac{L_{ac}}{\eta_{inv}}$$

$$L=\frac{L_{T}}{\eta_{bat}\cdot\eta_{c}}$$

Como valores orientativos pueden utilizarse

$\eta_{inv}=0.9$, $\eta_{r}=0.95$, $\eta_{bat}=0.85$ y $\eta_{c}=0.98$.

*** Distribución del consumo

[[../figs/ConsumoGamma.pdf]]

*** Relación entre el consumo y la fiabilidad

[[../figs/ConsumoLLP.pdf]]

** Escenarios
*** SHS 1
**** 120 Wh/dia
-  Iluminación

-  Radio

-  TV b/n,

-  Sin frigorífico

**** Valores recomendados 
$$\begin{aligned}
C_{A} & = & 1.1\\
3\leq & C_{s} & \leq5
\end{aligned}$$

*** SHS 2
**** 250 Wh/dia
-  Iluminación

-  Radio

-  TV color

-  Sin frigorífico

**** Valores recomendados 
$$\begin{aligned}
C_{A} & = & 1.1\\
3\leq & C_{s} & \leq5
\end{aligned}$$

*** SHS 3
**** 1000 Wh/dia
-  Iluminación

-  radio

-  TV color

-  Con frigorífico eficiente

**** Valores recomendados 
$$\begin{aligned}
C_{A} & = & 1.1\\
C_{S} & = & 5
\end{aligned}$$

*** Centrales

**** 
-  Todo AC

-  500 Wh/dia por vivienda.

**** Valores recomendados 
$$\begin{aligned}
C_{A} & = & 1.1\\
C_{S} & = & 5\end{aligned}$$
