#+TITLE: Sistemas Fotovoltaicos Autónomos
#+SUBTITLE: Conceptos Generales y Componentes

#+SETUPFILE: config.org
#+OPTIONS: H:3

* Conceptos Generales

*** Definición de un Sistema Autónomo

Un sistema fotovoltaico autónomo (SFA) produce energía eléctrica para *satisfacer el consumo de cargas eléctricas no conectadas a la red*, *empleando un sistema de acumulación energético* para hacer frente a los períodos en los que la generación es inferior al consumo.

*** Configuracion SHS

[[../figs/DiagramaUnifilarER_DC.pdf]]

*** Configuración AC

[[../figs/DiagramaUnifilarER_AC.pdf]]

*** Configuración DC+AC

[[../figs/DiagramaUnifilarER_AC_DC.pdf]]

*** Sistema Híbrido

[[../figs/DiagramaUnifilarER_Hibrido.pdf]]

* Acumulador Electroquímico

** Definiciones

*** Acumulador electroquímico

Un acumulador electroquímico es una bateria secundaria o recargable, capaz de almacenar energía eléctrica mediante una transformación en energía electroquímica. Sus principales funciones son:

-  *Autonomía*: satisface los requerimientos de consumo en cualquier momento, independientemente de la generación.

-  *Suministro de picos de intensidad*: cuando es necesario, puede suministrar valores de intensidad superiores a los que proporciona el generador FV.

-  *Estabilización del voltaje*: evita fluctuaciones dañinas para los equipos de consumo.

*** Definiciones

-  Capacidad nominal ($C_{nom}$) :: es la carga eléctrica que puede ser extraída de una batería hasta llegar a la descarga total.

-  Régimen de carga/descarga :: es la corriente aplicada a una batería para restablecer/extraer la capacidad nominal. Normalmente se presenta como un ratio entre la capacidad nominal y la corriente.

-  Estado de carga (SoC) :: de una batería es la capacidad de una batería parcialmente cargada, dividida por su capacidad nominal. Por tanto siempre será $0<SoC<1$.

*** Definiciones

-  Profundidad de descarga (PD) :: es el complemento del estado de carga.

-  Tensión de corte: :: es la tensión a la que finaliza la descarga de la batería. Depende del régimen de descarga y del tipo de batería.  Determina la profundidad de descarga máxima, $PD_{max}$, y por tanto, la capacidad útil, $C_{U}$, siendo $$C_{U}=PD_{max}\cdot C_{nom}$$
     
*** Definiciones

-  Eficiencia farádica :: es el ratio entre la carga extraída durante la descarga y la carga requerida para restablecer el estado inicial.

-  Eficiencia energética :: es el ratio entre la energía extraída durante la descarga y la energía requerida para restablecer el estado inicial.

** Principios de funcionamiento

*** Composición

Una batería de ácido-plomo se compone de:

-  Un *ánodo o electrodo positivo* con PbO$_{\text{2}}$

-  Un *cátodo o electrodo negativo* con Pb.

-  *Electrolito* a base de $H_{2}SO_{4}$ diluido en agua.

[[../figs/AcumuladorBN.pdf]]



*** Reacción Química REDOX
- Ánodo (+):

#+BEGIN_EXPORT latex
\[
\mathrm{PbO_{2}+SO_{4}^{2-}+H^{+}+2e^{-}
\xrightleftharpoons[\text{carga}]{\text{descarga}}
  PbSO_{4}+2H_{2}O}
\]
#+END_EXPORT

- Cátodo (-):
#+BEGIN_EXPORT latex
\[
\mathrm{Pb+SO_{4}^{2-}
\xrightleftharpoons[\text{carga}]{\text{descarga}}
PbSO_{4}+2e^{-}}
\]
#+END_EXPORT

- Global:
#+BEGIN_EXPORT latex
\[
\mathrm{Pb+PbO_{2}+2H_{2}SO_{4}
\xrightleftharpoons[\text{carga}]{\text{descarga}}
2PbSO_{4}+2H_{2}O}
\]
#+END_EXPORT


*** Descarga
#+BEGIN_EXPORT latex
\[
\mathrm{Pb+PbO_{2}+2H_{2}SO_{4}} \rightarrow \mathrm{2PbSO_{4}+2H_{2}O}
\]
#+END_EXPORT

- *Consumo de electrolito* (disminuye su densidad)

- *Cambios de volumen* de los materiales activos.

- *Descargas repetidas* producen *pérdida de material activo* y degradación de las placas. 

- Si la descarga es muy rápida y la bateria permanece descarga largo tiempo, el sulfato cristaliza y no es recuperable (*sulfatación*).

*** Carga
#+BEGIN_EXPORT latex
\[
\mathrm{2PbSO_{4}+2H_{2}O} \rightarrow \mathrm{Pb+PbO_{2}+2H_{2}SO_{4}} 
\]
#+END_EXPORT

- Con largos períodos en estados parciales de carga, el ácido se concentra en el fondo por gravedad (*estratificación*)

  - Las reacciones no se producen de igual forma en toda la extensión de las placas, lo que realimenta el proceso.

  - Puede reducirse mediante un *gaseo controlado*.

- Al terminar el proceso de carga se produce la electrolisis del agua, con liberación de oxigeno e hidrógeno (*gaseo*):

  - Pérdida de agua del electrolito (hay que reponerla)

  - Homogeneización del electrolito por agitación (reduce la estratificación)

** Modelo eléctrico
*** Fuente de tensión
- Una batería de ácido-plomo puede ser modelada como una fuente de tensión, $V_{BI}$, en serie con una resistencia, $R_{BI}$.

[[file:../figs/Bateria.pdf]]

*** Densidad del electrolito y Tensión en Abierto

**** La medida de la tensión en circuito abierto de la batería es un método común para estimar el estado de carga de una batería.

- $V_{BI}=\rho_{e}+0.84$

- Baterías cargadas:

  - $\SI{1.2}{\gram\per\cm\cubed} \leq \rho_{e}  \leq \SI{1.28}{\gram\per\cm\cubed}$.
  - $\SI{2.04}{\volt} \leq V_{BI} \leq \SI{2.12}{\volt}$.
- *Hay que corregir con la temperatura*

*** Evolución de la tensión durante un proceso de descarga

[[../figs/Bateria_SOCyDescarga.pdf]]

*** Evolución de la tensión en un proceso de carga

[[../figs/Bateria_CorrYTemp.pdf]]


** Efecto de la temperatura

*** Temperatura baja

   -  El electrolito se hace más viscoso y decrece la movilidad de los iones (aumenta la resistencia eléctrica)

   -  *Baja la capacidad* para un regimen de descarga determinado a razón de 1%/ºC

   -  Si el electrolito se congela, no hay movimiento iónico, y por tanto la capacidad es nula. Para evitarlo, *hay que recurrir a densidades altas de electrolito en lugares muy frios*.

*** Temperatura alta

   - *Acelera las reacciones, favoreciendo la corrosión*. Por tanto, decrece la vida de la batería.

   - En *climas cálidos*, se debe optar por *bajas concentraciones de electrolito* (que se ve compensada por la mayor movilidad iónica debida a la alta temperatura).

   - *Baja el valor de tensión al que empieza la sobrecarga* debido a que la resistencia interna baja con la temperatura.

     - Hay que corregir el umbral de corte con la temperatura (se puede utilizar la ambiente como referencia)

*** Capacidad según el regimen de descarga y la temperatura

[[../figs/Bateria_Capacidad.pdf]]

** Ciclado 
*** Definición

- El ciclado es el *proceso* por el que un acumulador es *continuamente cargado y descargado durante su vida.*

- Produce *degradación* de la batería por *perdida de material activo* (descargas repetidas) y *estratificación*.

*** Resistencia al ciclado

Los factores que influyen sobre la resistencia del acumulador al ciclado son: 
-  *La profundidad de descarga*: las descargas profundas disminuyen los ciclos de vida de una batería.

-  *El régimen de carga*: cuanto mayor es el régimen de carga y el porcentaje de sobrecarga, menor será la vida alcanzada.

-  *La temperatura*: las temperaturas altas aceleran la corrosión en los electrodos disminuyendo los ciclos de vida.

** Tipos de acumuladores

*** Características generales

-  Un acumulador incorporado a un SFA debe ser *capaz de funcionar sometido a ciclados diarios y anuales de carga y descarga*, teniendo en cuenta que la carga entregada por el generador depende directamente de la radiación (variable en los períodos intradiario e intraanual).

-  Debido a las posibles fluctuaciones en la carga aportada, es probable que se sucedan *periodos prolongados en carga parcial*.

-  Es habitual que las *descargas sean a baja intensidad con periodos de descarga largos*, típicamente en torno a las 100 horas.

*** Baterías de arranque

- Habitualmente empleadas en *automóviles*

- Fácilmente localizables en cualquier *mercado local a bajo precio* (relativo)

- *Opción frecuentemente empleada* en sistemas de electrificación rural de *pequeño tamaño* o como *reemplazo* de baterías estropeadas

- Buen comportamiento en descarga de alta intensidad y a bajas temperaturas

- *No son resistentes frente al ciclado*

*** Baterías de tracción

-  Empleadas, por ejemplo, en *carretillas elevadoras*.

-  Soportan *elevado número de ciclos profundos de carga-descarga*.

-  Requieren *aportación de agua* y *mantenimiento frecuente*.

-  Empleo en SFA sólo cuando exista mantenimiento regular.

*** Baterías estacionarias

-  Empleadas en sistemas de alimentación ininterrumpida (*UPS*) o instalaciones remotas (por ejemplo, radioenlaces).

-  Funcionan en *régimen de flotación*.

-  Gran reserva de electrolito aunque realizan poco uso de agua.

-  *Resistencia a la corrosión* y elevada fiabilidad.

-  *Opción muy interesante para SFA*. Precio más elevado frente a las anteriores opciones.

*** Elección de batería

**** Criterios a tener en cuenta

   - *Requisitos técnicos* (capacidad, tipo de ciclado, etc.)

   - *Coste del sistema*

   - Recursos de *mantenimiento*.

   - *Disponibilidad de reemplazo* en el mercado local

   - Capacidad de intervención del usuario.

**** Para aplicaciones fotovoltaicas se recomienda

   - *Baterías estacionarias aireadas de placa positiva tubular*

   - *Baterías SLI modificadas*: placas más gruesas, mayor cantidad de
     electrolito por encima de las placas, con aleación de Pb-Sb en la
     rejilla y vaso transparente.


** Composición

*** Composición

[[../figs/AcumuladorBN.pdf]]

*** Rejillas

- Dan *soporte estructural a los materiales activos*

- *Conducen la corriente eléctrica* hacia el circuito externo.

- Están fabricadas en *aleaciones de Plomo*.

  - La *aleación de plomo-antimonio* presenta buen comportamiento en
   ciclado y en descarga profunda.

- La *rejilla negativa* es *plana*

- La *rejilla positiva* puede ser *plana* (operación en flotación) o
  *tubular* (operación en ciclado).

*** Materiales activos

- Los materiales activos participan en las reacciones químicas.
- Están *adheridos a las rejillas*.
- Deben ser *porosos* para permitir la penetración del electrolito

*** Electrolito
- El *electrolito* participa en la reacción y *realiza el transporte
 iónico* para cerrar el ciclo de corriente de las reacciones.

- Para *reducir la resistencia eléctrica* del electrolito, su *densidad
 debe ser alta*,

- Pero *un electrolito de alta densidad es muy agresivo* (produce
  corrosión en la rejilla positiva).

- Los acumuladores estacionarios utilizan densidades más bajas que
 los de arranque (altos regímenes de descarga).

- El electrolito *puede ser líquido* (aireadas) *o inmovilizado*
 (selladas).

*** Separadores

- Los separadores *aislan las placas de diferente polaridad pero
  permiten el movimiento iónico a través suyo*.
- Requisitos:
  - Resistencia mecánica
  - Permeables y porosos.
  - Resistentes a la oxidación
  - Aislantes eléctricos
  - Sin contaminantes

* Regulador de carga

*** Definición

Un regulador de carga es un equipo electrónico capaz de *evitar la sobrecarga y la descarga excesiva de un acumulador* desconectando al acumulador del generador o del consumo *cuando se alcanzan determinados estados umbral, generalmente determinados por la tensión en bornes*.

*** Regulador Serie y paralelo

- Regulador Serie
#+ATTR_LATEX: :height 0.3\textheight
[[../figs/ReguladorSerie.pdf]]

- Regulador Paralelo
#+ATTR_LATEX: :height 0.3\textheight
[[../figs/ReguladorParalelo.pdf]]


*** Ciclo de carga
#+ATTR_LATEX: :height 0.5\textheight
[[../figs/HisteresisCargaRegulador.pdf]]

-  $U_{sc}$ debe estar en el rango de $\SI{2.3}{\volt}$ a $\SI{2.4}{\volt}$ por vaso a $\SI{25}{\celsius}$.

-  $U_{rc}$ debe estar en el rango de $\SI{2.15}{\volt}$ a $\SI{2.2}{\volt}$ por vaso a $\SI{25}{\celsius}$.

-  *Deben corregirse por temperatura* a razón de $\SI{4}{\milli\volt\per\celsius}$ a $\SI{5}{\milli\volt\per\celsius}$ por vaso.

*** Ciclo de descarga
#+ATTR_LATEX: :height 0.5\textheight
[[../figs/HisteresisDescargaRegulador.pdf]]

Los umbrales deben adaptarse a cada tipo de batería (mediante ensayos, o recomendaciones del fabricante)

* Luminarias

*** Funcionamiento

- Una lámpara fluorescente convencional está formada por un *tubo de descarga con gas a baja presión*, un *recubrimiento de una mezcla de polvos fluorescentes* y *dos electrodos* en los extremos.

- Un *circuito auxiliar (balasto)* cumple dos funciones principales:

  - *Proporciona la tensión de encendido* necesaria para que fluya corriente por el tubo.

  - *Regula la corriente* que circula por el tubo una vez que se ha producido el encendido para evitar su destrucción.

*** Degradación

- *El proceso de encendido es el que más contribuye a la degradación* de los tubos fluorescentes.
- Un método alternativo consiste en *precalentar los electrodos* (con un circuito basado en un condensador y en una resistencia) facilitando el paso a la etapa de emisión termoiónica, y acortando el período de encencedido.

*** Fotometría

-  Flujo :: radiante es la potencia emitida por la fuente luminosa (Unidad: Watio)

-  Flujo :: luminoso es la potencia emitida capaz de producir sensación luminosa en el ojo humano (Unidad: Lumen)

-  Iluminación :: de una superficie sobre la que incide un flujo luminoso es el ratio entre flujo y superficie (Unidad: lux, $\si{\lumen\per\watt\squared}$).

-  Eficiencia :: de la luminaria (tubo y balasto) es la relación entre potencia eléctrica consumida por el conjunto y la potencia luminosa producida (Unidad: $\si{\lumen\per\watt}$). 

*** Requisitos
- Recomendable eficiencia superior a 50 $\si{\lumen\per\watt}$

  - *Debe ser superior a 35 $\si{\lumen\per\watt}$*.

- Recomendable resistencia a un mínimo de 10000 ciclos de encendido y apagado

  - *Deberá resistir 5000 ciclos.*


