* Energía Producida por un SFCR

** Procedimiento de cálculo

*** Potencia en un SFCR

Potencia a la Salida del Generador FV

$$P_{dc} = A_g \cdot \eta_g(G_{ef}, T_a) \cdot  G_{ef} = %
      \frac{\eta_g(G_{ef}, T_a)}{\eta_g^*} \cdot \frac{G_{ef}}{G^*} \cdot P_g^*$$

Potencia a la Salida del Inversor

$$P_{ac} = P_{dc} \cdot \eta_{inv}(P_{dc}, V_{dc}) =  P_{dc} \cdot \eta_{inv}(G_{ef}, T_a)$$

Energía Producida por un SFCR

$$E_{ac} = \int_T \frac{\eta_g(G_{ef}, T_a)}{\eta_g^*} \cdot
      \frac{G_{ef}}{G^*} \cdot \eta_{inv}(G_{ef}, T_a) \cdot P_g^* \mathrm{dt}$$

*** Energía producida

$$E_{ac}=P_{g}^{*}\cdot\frac{G_{ef}}{G^*}\cdot PR\cdot (1-FS)$$

-  $E_{ac}$ es la *energía producida *en un periodo ()

-  $G^*$ es la *irradiancia* en condiciones estándar de medida (STC,
   $G_{stc}=\SI{1}{\kilo\watt\per\meter\squared}$,
   $T_c=\SI{25}{\celsius}$)

-  $P_{g}^{*}$ es la *potencia nominal* del generador FV
   ($\si{\kilo\wattpeak}$) en STC

-  $G_{ef}$ es la *irradiación efectiva incidente* en el plano del
   generador ()

-  $PR$ es el *rendimiento del sistema* o /performance ratio/

-  $FS$ es el *factor de sombras*

*** Productividad

En algunas ocasiones se habla de *productividad* del sistema, $Y_{f}$,
que es el cociente entre energía producida y potencia nominal del
sistema:
$$Y_{f}=\frac{E_{ac}}{P_{g}^{*}}\,(\si{\kilo\watthour\per\kilo\wattpeak})$$

*** Performance Ratio

-  Está concebido para incluir todas las pérdidas que no tienen
   dependencia con las condiciones meteorológicas.

-  Este factor "puede" caracterizar el funcionamiento de un sistema
   independientemente de la localidad.

-  En sentido estricto no es cierto porque sí hay relación con la
   meteorología del lugar.

-  Sin embargo, dado que estos factores son de segundo orden comparados
   con la relación entre potencia e irradiancia, suele aceptarse que el
   PR sirve para caracterizar la calidad de un sistema fotovoltaico.

*** Performance Ratio

Desglose de pérdidas

-  *Dispersión de parámetros* entre los módulos que componen el
   generador (2-4%)

-  *Tolerancia de potencia* de los módulos respecto a sus
   características nominales (3%)

-  *Temperatura* de funcionamiento de los módulos (5-8%)

-  Conversión DC/AC realizada por el *inversor* (8-12%)

-  *Efecto Joule* en los cables (2-3%)

-  Conversión BT/MT realizada por el *transformador* (2-3%)

-  *Disponibilidad* del sistema (0,5-1%)

*** Performance Ratio

Valores reales

-  El análisis de funcionamiento de diversos sistemas FV europeos ha
   mostrado que el rango de valores que toma el /performance ratio/ es
   bastante amplio, con mínimos de 0,4 y máximos de 0,85.

-  Para sistemas instalados desde 1996, *el valor promedio ha sido de
   0,74*.

*** Factor de sombras

-  *El factor de sombras suele tomar valores alrededor del 2 al 4%*,
   tanto en instalaciones estáticas como de seguimiento.

-  En casos específicos este factor puede ser más alto (por ejemplo,
   debido a la existencia de edificios cercanos, o en aquellas plantas
   con un nivel de ocupación de terreno superior al óptimo).

* Sombras y ocupación de terreno

** Sombras Lejanas

[plain]

*** Método CTE

[[../Figuras/Figuras_Externas/SombraIES]]

** Sombras Cercanas: sistemas estáticos

*** Sombras entre filas

[[../Figuras/Figuras_Externas/SombraEstaticaInclinado2]]

*** Sombras entre filas

Suele establecerse un objetivo de *4 horas de sol en torno al mediodía
del solsticio de invierno libres de sombra*.

La longitud de la sombra de un obstáculo se mide
con:$$d=\frac{h}{\tan\gamma_{s}}$$

En el mediodía del solsticio de invierno
$$\gamma_{s}=90-23.45-\phi\simeq67-\phi$$ Para 2 horas antes y después:

$$d_{min}=\frac{h}{\tan(61\degree-\phi)}$$

** Sombras Cercanas: sistemas de seguimiento

*** Separación de seguidores Doble Eje

[[../Figuras/Sombras2X]]

[[../Figuras/DimensionesSeguidorSombra]]

$$b=\frac{L}{W}$$ $$ROT=\frac{L_{ns}\cdot L_{eo}}{b}$$

$$E_{ac}=f(ROT)??$$

[plain]

*** Separación de Seguidores Doble Eje

[t]

$$b=\frac{L}{W}=0.475$$

$$ROT=\frac{L_{ns}\cdot L_{eo}}{b}$$

[[../Figuras/AbacoSeguidor2X_Ene10]]

[plain]

*** Ocupación de Terreno

**** ROT para diferentes valores de Leo

[t]

$$b=\frac{L}{W}=0.475$$

$$ROT=\frac{L_{ns}\cdot L_{eo}}{b}$$

[[../Figuras/AbacoSeguidor2X_Leo_Ene10]]

[plain]

*** Ocupación de Terreno

**** ROT para diferentes valores de Lns

[t]

$$b=\frac{L}{W}=0.475$$

$$ROT=\frac{L_{ns}\cdot L_{eo}}{b}$$

[[../Figuras/AbacoSeguidor2X_Lns_Ene10]]

** Seguidores de eje horizontal NS

*** Separación de Seguidores Eje Horizontal

[[../Figuras/SombrasHoriz]]

$$W=\infty$$ $$ROT=L_{eo}/L$$

*** Separación de Seguidores Horizontal N-S

**** Sombra

[[../Figuras/AbacoSeguidorHorizSombra_Ene10]]

*** Backtracking

-  El *sombreado* en un generador puede producir problemas por el efecto
   de *punto caliente*.

-  En seguidores de eje horizontal se puede *evitar la incidencia de
   sombras* en cualquier instante mediante el "*backtracking*":

   -  Al *amanecer* el seguidor está en posición *horizontal*.

   -  Según avanza el día el seguidor gira en *sentido contrario al
      movimiento solar para evitar las sombras*.

   -  En un determinado momento se cruza con el sol y puede continuar el
      movimiento "convencional".

   -  En un instante de la tarde debe volver a cambiar el sentido hasta
      la *horizontal en la noche*.

*** Backtracking

[[../Figuras/BackTracking]]

*** Separación de Seguidores Horizontal N-S

**** Backtracking

[[../Figuras/AbacoHorizBT_Ene10]]

** Elección de separaciones

*** Elección de separaciones

Elección de separaciones

La *separación óptima* entre elementos (seguidores o estructuras
estáticas) es aquella que conduce al *mínimo valor del coste de la
energía* producida por el sistema:

-  Con mayor separación disminuyen las *pérdidas por sombreado mutuo*,
   aumenta la productividad del sistema.

-  Con mayor separación aumentan los *costes relacionados con el area
   ocupada* por unidad de potencia.

-  Con mayor separación aumentan los *costes relacionados con los
   elementos de unión entre estructuras* (cableado, canalizaciones,
   zanjas).

*** Elección de separaciones

-  Esta separación óptima *depende* de las *estructuras elegidas* y de
   las *condiciones económicas* de los elementos.

-  La separación finalmente elegida debe *tomar en consideración las
   condiciones del terreno* (fronteras, irregularidades, vaguadas, etc.)

[plain]

*** Radiación promedio

$$G_{ef, av} = 1/24 \cdot \left( 10 \cdot G_{ef,0} + 5 \cdot G_{ef,A}
      + G_{ef,B} + 2 \cdot G_{ef,C} + G_{ef,D} + 5 \cdot G_{ef,E} \right)$$

4cm

[[../Figuras/plantConfiguration]]

6cm [[../Figuras/6trackers]]

[plain]

*** Cableado

[[../Figuras/wiring]]

$$\begin{aligned}
    \Delta U_{inv} &= \frac{\Delta U}{1+\sqrt{\frac{\sum_{i=1}^n
          L_{i}^2 \cdot I_{i}}{L_{inv}^2 \cdot I_{inv}}}} \\
    \Delta U_{inv} &+ \Delta U_i = \Delta U\\
    S_{inv} &= 2 \cdot \rho \cdot \frac{L_{inv} \cdot
      I_{inv}}{\Delta U_{inv}} \\
    S_{i} &= 2 \cdot \rho \cdot \frac{L_{i} \cdot I_i}{\Delta U_i}
  \end{aligned}$$

[plain]

*** Coste de la energía producida

$$\begin{aligned}
    C_E &= \frac{C_P}{E_{AC}}\\
    C_p &= C_c + C_A + C_{PV}
  \end{aligned}$$

5cm

[[../Figuras/WiringCosts.pdf]]

5cm $C_{PV}$ entre $\SI{2.5}{\text{\texteuro}\per\watt}$ y
$\SI{5}{\text{\texteuro}\per\watt}$

$C_A$ entre $\SI{1.5}{\text{\texteuro}\per\meter\squared}$ y
$\SI{4}{\text{\texteuro}\per\meter\squared}$

[plain]

[[../Figuras/matrix-300dpi]]

[plain]

*** Resultados

[[../Figuras/GRRoptim]]

* Resumen

*** Ocupación de terreno y productividad

ccc SFCR & ROT & ProductividadEstático & 2 & 1Eje Horizontal NS & 4 &
1,05-1,2Doble Eje & 6 & 1,3-1,5
