#+TITLE: Energía Producida por un SFCR
#+SUBTITLE: Energía Solar Fotovoltaica
#+SETUPFILE: config.org
#+OPTIONS: H:2

* Energía Producida por un SFCR

** Nomenclatura

- $E_{ac}$: energía producida en un periodo.
- $G_{stc}, G^*$: irradiancia en condiciones estándar de medida (STC,
  $G_{stc}=\SI{1}{\kilo\watt\per\meter\squared}$,
  $T^*_c=\SI{25}{\celsius}$)
- $P_{g}^{*}$: potencia nominal del generador FV
  ($\si{\kilo\wattpeak}$) en STC
- $G_{inc}$: irradiación incidente en el plano del
  generador (no incluye suciedad, pérdidas de reflexión ni sombreado)
- $G_{ef}$: irradiación efectiva incidente en el plano del
  generador
- $\eta_g$: eficiencia del generador
- $\eta_{inv}$: eficiencia del inversor
- $A_g$: área del generador

** Potencia y Energía del Generador

- *Potencia* a la Salida del Generador FV
#+begin_export latex
\[
  P_{dc} = A_g \cdot \eta_g(G_{ef}, T_a) \cdot  G_{ef} = %
  \frac{\eta_g(G_{ef}, T_a)}{\eta_g^*} \cdot \frac{G_{ef}}{G^*} \cdot P_g^*
\]
#+end_export

- *Energía* a la Salida del Generador FV

#+begin_export latex
\[
  E_{dc} = \int_T \frac{\eta_g(G_{ef}, T_a)}{\eta_g^*} \cdot
  \frac{G_{ef}}{G^*} \cdot P_g^*\quad \mathrm{dt}
\]
#+end_export

** Potencia y Energía del Sistema
- *Potencia* a la Salida del Inversor
#+begin_export latex
\[
P_{ac} = P_{dc} \cdot \eta_{inv}(P_{dc}, V_{dc}) =  P_{dc} \cdot \eta_{inv}(G_{ef}, T_a)
\]
#+end_export

- *Energía* Producida por un SFCR
#+begin_export latex
\[
  E_{ac} = \int_T \frac{\eta_g(G_{ef}, T_a)}{\eta_g^*} \cdot
  \frac{G_{ef}}{G^*} \cdot \eta_{inv}(G_{ef}, T_a) \cdot P_g^*\quad \mathrm{dt}
\]
#+end_export

* Productividades y Pérdidas

** Planteamiento

- Las *productividades* son relaciones entre una cantidad de energía y la potencia nominal $P_g^*$.
  - Indican el funcionamiento real del SFCR en relación con su capacidad asignada.
- Las *pérdidas* se calculan restando las productividades.
  - Representan la cantidad de tiempo que el SFCR necesitaría para funcionar a $P_g^*$ para compensar las pérdidas respectivas durante el periodo correspondiente.
** Productividades

- Productividad del Generador 
  #+begin_export latex
  \[
    Y_a = \frac{E_{dc}}{P_g^*} \quad [\unit{\kilo\watthour\per\kilo\wattpeak}]
  \]
  #+end_export

- Productividad del Sistema
  #+begin_export latex
  \[
    Y_f = \frac{E_{ac}}{P_g^*} \quad [\unit{\kilo\watthour\per\kilo\wattpeak}]
  \]
  #+end_export

- Productividad de Referencia[fn:1]
#+begin_export latex
\begin{align*}
  E_{ref} &= P_g^* \cdot \frac{G_{inc}}{G_{stc}}\\
  Y_r &= \frac{E_{ref}}{P_g^*} = \frac{G_{inc}}{G_{stc}} \quad [\unit{\kilo\watthour\per\kilo\watt}]
\end{align*}
  #+end_export
** Pérdidas de Rendimiento

*** Pérdidas de captación del campo fotovoltaico.

  #+begin_export latex
  \[
    L_C = Y_r - Y_a
  \]
  #+end_export
  Incluye pérdidas ópticas (suciedad, reflexión, sombreado), y pérdidas del generador (temperatura, cableado, tolerancia de potencia, dispersión de parámetros, LID, envejecimiento).

*** Pérdidas en el balance del sistema
  #+begin_export latex
  \[
    L_s = Y_a - Y_f
  \]
  #+end_export
  Incluye pérdidas por eficiencia e interrupciones del inversor, cableado,  y transformador.

  
** Resumen

#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/SankeyDiagrama_SFCR.pdf]]

* Métricas de Rendimiento

** /Performance Ratio/ o rendimiento global

#+begin_export latex
\[
  PR = \frac{Y_f}{Y_r} = \frac{E_{ac}}{P_g^* \cdot \frac{G_{inc}}{G_{stc}}}
\]
#+end_export

- Está concebido para incluir todas las *pérdidas que no tienen
 dependencia con las condiciones meteorológicas*.

- Este factor /puede/ caracterizar el funcionamiento de un sistema
  *independientemente de la localidad*.

- En sentido estricto no es cierto porque sí hay *relación con la temperatura*.

  - Un mismo sistema tendrá un PR más alto en un lugar de clima frío que en un lugar de clima cálido.

  - El PR de un sistema es estacional (más alto en invierno que en verano).

** Valores del PR

- El análisis de funcionamiento de diversos sistemas FV europeos ha
  mostrado que el rango de valores que toma el /performance ratio/ es
  bastante amplio, con mínimos de 0,4 y máximos de 0,85.

- Para sistemas instalados entre 1980 a 1990, *el valor promedio ha sido de
  0,7*.

- Para sistemas instalados entre 2005 a 2012, *el valor promedio ha
  sido de 0,8*.


** Rendimiento Global $\qty{25}{\celsius}$

#+begin_export latex
\[
  PR_{25} = \frac{E_{ac}}{\sum_i \left\{P_g^* \cdot \left[1 + \gamma_P \cdot(T_{c,i} - 25)\right]\cdot G_{ef,i}/G_{stc} \cdot \Delta t \right\}}
\]
#+end_export
- Se introduce una corrección con la temperatura utilizando el coeficiente $\gamma$ de dependencia de la potencia del módulo con la temperatura.
- $\Delta t$ es el intervalo temporal de medida.
- No elimina totalmente la dependencia estacional porque hay otros efectos estacionales (sombras).

* Footnotes

[fn:1]Atención: se define con la radiación incidente, y no con la efectiva. 
