#+TITLE: Actividad: cálculo de radiación
#+SUBTITLE: Energía Solar Fotovoltaica
#+AUTHOR:    Oscar Perpiñán Lamigueiro
#+EMAIL:     oscar.perpinan@upm.es
#+DATE: 
#+LANGUAGE:  en
#+OPTIONS:   num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LATEX_HEADER: \usepackage{mathpazo}

En esta actividad vas a estimar las medias mensuales de la radiación global incidente en el plano horizontal y en el plano de un generador.

Para el cálculo de la *radiación en el plano horizontal* seguiremos el siguiente itinerario (en cursiva se indican los apartados opcionales):

1. Obtén series temporales de *medidas diarias* de radiación solar de 3 estaciones meteorológicas (recomendable longitud de 10 años).
2. Filtra cada serie empleando límites físicos.
3. Obtén una serie temporal *diaria* representativa de la región calculando la media de las tres series temporales.
4. Compara esta serie temporal media con las series temporales de cada estación usando métricas estadísticas (MBD, RMSD, MAD).
5. Elige una localización dentro del perímetro definido por las tres estaciones. Obtén las *12 medias mensuales* en esta localización empleando interpolación espacial (IDW) a partir de las *12 medias mensuales* de la radiación filtrada de cada estación (punto 2)
6. /Obtén medias temporales de radiación solar de un servicio satelital (preferiblemente CMSAF,  empleando QGis o software similar) para una región que cubra las tres estaciones[fn:1]./
7. /Compara las medias mensuales de las tres estaciones con las estimaciones satelitales empleando métricas estadísticas./
8. /Combina la estimación satelital en la localización del punto 5 con las medias mensuales obtenidas en ese punto./

A continuación, realizaremos el cálculo de la *radiación en el plano del generador*. Este generador está localizado en el hemisferio norte, orientado al sur y con una inclinación de 30º. Seguiremos el siguiente itinerario:

1. En la localización elegida en el punto 5 anterior, calcula la declinación, duración del día, e irradiación extra-atmosférica diaria en el plano horizontal *para los días promedio*.
2. Calcula el índice de claridad y fracción de difusa para las 12 medias mensuales obtenidas en el punto 8 (o, en su defecto, punto 5). Con estos parámetros obtén las medias mensuales de irradiación difusa y directa diarias en el plano horizontal.
3. Calcula el coseno del ángulo cenital y el coseno del ángulo de incidencia para cada día promedio (mes). Deberías obtener 24 valores por día (un total de 12·24=288 valores por parámetro).
4. Calcula los perfiles intradiaarios rd y rg para cada dia promedio (mes). Deberías obtener 24 valores por mes (un total de 12·24=288 valores por parámetro).
5. Obtén los perfiles de irradiancia difusa, global y diaria para cada día promedio (mes). Deberías obtener 24 valores por mes (un total de 12·24=288 valores por componente).
6. Obtén la irradiancia en el plano del generador realizando la transformación de los valores del punto 12 del plano horizontal al plano del generador.
7. Suma los resultados del paso anterior para obtener las 12 medias mensuales de radiación diaria (global, difusa y directa) en el plano del generador. Comprueba que estos resultados son superiores a los valores de la radiación en el plano horizontal.


* Footnotes

[fn:1] Los datos de radiación proporcionados por CMSAF son medias diarias de *irradiancia* ($W/m^2$). Por tanto, debes multiplicarlos por 24 para obtener valores diarios de *irradiación*.
